### ISSUE TITLE
Custom headers is not sent on request

### ISSUE THREAD

**Issue by orlandokj** [oshosanya/graphql-export#12]
Hello,
I've tried to execute this tool with custom headers but it does not work as expected. 
The headers are being sent on the body of the HTTP request, I'm attaching the output here.
[output.txt](https://github.com/oshosanya/graphql-export/files/5449111/output.txt)

**Comment by oshosanya** [comment]
`Could not find a required APP in the request, identified by HEADER client_id.`

This is the exact error from the server. You need to pass the exact client id, as your header is `-H "client_id: client_id" "Authorization: Basic my_credentials"` rather than the exact client id like so; `-H "client_id: x325bbvvet" "Authorization: Basic my_credentials"`

**Comment by orlandokj** [comment]
Did you look at the body on the output file? I removed the client id for security. But the problem is the header is not sent at all.
Looking in the source code [here](https://github.com/oshosanya/graphql-export/blob/078fb644f06394c1f3b5908c507789d71214c729/src/exporters/index.ts#L132) you can see that the body is {query: "...", headers: "..."}, the header should be sent on the next argument.
